package OOP;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.text.DecimalFormat;
import javax.swing.*;

/**
 *
 * @author henry
 */
public class itemsPage extends javax.swing.JFrame {

    private double gDonut = 1;
    private double cDonut = 1.50;
    private double sDonut = 1.50;
    
    private double hChocolate = 2;
    private double cShake = 2.5;
    private double sShake = 2.5;

    private double donuts;
    private double drinks;
    private double totalOfDonutsDrinks;
    private double allTotal;

    
    /**
     * Creates new form itemsPage
     */
    public itemsPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlRedbar1 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblSignUpScreen = new javax.swing.JLabel();
        btnConfirmation = new javax.swing.JButton();
        lblUN1 = new javax.swing.JLabel();
        lblDonuts = new javax.swing.JLabel();
        lblChocolateDonut = new javax.swing.JLabel();
        lblStrawberryDonut = new javax.swing.JLabel();
        lblHotChocolate = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lblGlazedDonut2 = new javax.swing.JLabel();
        lblChocolateShake = new javax.swing.JLabel();
        lblStrawberryShake = new javax.swing.JLabel();
        txtGdonut = new javax.swing.JTextField();
        txtCdonut = new javax.swing.JTextField();
        txtSdonut = new javax.swing.JTextField();
        txtHotChoco = new javax.swing.JTextField();
        txtChocShake = new javax.swing.JTextField();
        txtStrawShake = new javax.swing.JTextField();
        btnGoBack = new javax.swing.JButton();
        lblType = new javax.swing.JLabel();
        lblType2 = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblAmount2 = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        lblGlazedDonut7 = new javax.swing.JLabel();
        lblGlazedDonut8 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnAddUp = new javax.swing.JButton();
        lblAmountPaid = new javax.swing.JLabel();
        lblTaxation = new javax.swing.JLabel();
        lblTheTotal = new javax.swing.JLabel();
        lblTheSubTotal = new javax.swing.JLabel();
        txtAmountPaid = new javax.swing.JTextField();
        lblTax20 = new javax.swing.JLabel();
        cbbPaymentType = new javax.swing.JComboBox<>();
        lblTax = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        pnlRedbar1.setBackground(new java.awt.Color(51, 255, 204));

        lblExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblExit.setForeground(java.awt.Color.white);
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(java.awt.Color.white);
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblSignUpScreen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSignUpScreen.setForeground(java.awt.Color.white);
        lblSignUpScreen.setText("ORDER MENU");

        javax.swing.GroupLayout pnlRedbar1Layout = new javax.swing.GroupLayout(pnlRedbar1);
        pnlRedbar1.setLayout(pnlRedbar1Layout);
        pnlRedbar1Layout.setHorizontalGroup(
            pnlRedbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRedbar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSignUpScreen)
                .addGap(55, 55, 55))
        );
        pnlRedbar1Layout.setVerticalGroup(
            pnlRedbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRedbar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRedbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSignUpScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnConfirmation.setBackground(new java.awt.Color(51, 255, 204));
        btnConfirmation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirmation.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmation.setText("Confirm");
        btnConfirmation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmationMouseClicked(evt);
            }
        });
        btnConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmationActionPerformed(evt);
            }
        });

        lblUN1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUN1.setForeground(new java.awt.Color(255, 255, 255));
        lblUN1.setText("Drinks");

        lblDonuts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDonuts.setForeground(new java.awt.Color(255, 255, 255));
        lblDonuts.setText("Donuts");

        lblChocolateDonut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChocolateDonut.setForeground(new java.awt.Color(255, 255, 255));
        lblChocolateDonut.setText("Chocolate Donut");

        lblStrawberryDonut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStrawberryDonut.setForeground(new java.awt.Color(255, 255, 255));
        lblStrawberryDonut.setText("Strawberry Donut");

        lblHotChocolate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHotChocolate.setForeground(new java.awt.Color(255, 255, 255));
        lblHotChocolate.setText("Hot Chocolate");

        lblGlazedDonut2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGlazedDonut2.setForeground(new java.awt.Color(255, 255, 255));
        lblGlazedDonut2.setText("Glazed Donut");

        lblChocolateShake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChocolateShake.setForeground(new java.awt.Color(255, 255, 255));
        lblChocolateShake.setText("Chocolate Shake");

        lblStrawberryShake.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStrawberryShake.setForeground(new java.awt.Color(255, 255, 255));
        lblStrawberryShake.setText("Strawberry Shake");

        txtGdonut.setText("0");

        txtCdonut.setText("0");

        txtSdonut.setText("0");

        txtHotChoco.setText("0");

        txtChocShake.setText("0");

        txtStrawShake.setText("0");

        btnGoBack.setBackground(new java.awt.Color(51, 255, 204));
        btnGoBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Go Back");
        btnGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoBackMouseClicked(evt);
            }
        });
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        lblType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblType.setForeground(new java.awt.Color(255, 255, 255));
        lblType.setText("Type");

        lblType2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblType2.setForeground(new java.awt.Color(255, 255, 255));
        lblType2.setText("Type");

        lblAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount.setText("Amount");

        lblAmount2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAmount2.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount2.setText("Amount");

        lblPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblPayment.setText("Payment");

        lblGlazedDonut7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGlazedDonut7.setForeground(new java.awt.Color(255, 255, 255));
        lblGlazedDonut7.setText("Change:");

        lblGlazedDonut8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGlazedDonut8.setForeground(new java.awt.Color(255, 255, 255));
        lblGlazedDonut8.setText("Payment Type:");

        btnReset.setBackground(new java.awt.Color(51, 255, 204));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAddUp.setBackground(new java.awt.Color(51, 255, 204));
        btnAddUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddUp.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUp.setText("Add Up");
        btnAddUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUpMouseClicked(evt);
            }
        });
        btnAddUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUpActionPerformed(evt);
            }
        });

        lblAmountPaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAmountPaid.setForeground(new java.awt.Color(255, 255, 255));
        lblAmountPaid.setText("Amount Paid:");

        lblTaxation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTaxation.setForeground(new java.awt.Color(255, 255, 255));
        lblTaxation.setText("Tax:");

        lblTheTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTheTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTheTotal.setText("Total:");

        lblTheSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTheSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTheSubTotal.setText("Sub-Total:");

        txtAmountPaid.setText("0");

        lblTax20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTax20.setForeground(new java.awt.Color(255, 255, 255));
        lblTax20.setText("Tax = 20%");

        cbbPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Payment", "Cash", "Card" }));
        cbbPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPaymentTypeActionPerformed(evt);
            }
        });

        lblTax.setBackground(java.awt.Color.white);
        lblTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTax.setForeground(java.awt.Color.white);

        lblSub.setBackground(java.awt.Color.white);
        lblSub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSub.setForeground(java.awt.Color.white);

        lblTotal.setBackground(java.awt.Color.white);
        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setForeground(java.awt.Color.white);

        lblChange.setBackground(java.awt.Color.white);
        lblChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChange.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRedbar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDonuts, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblStrawberryDonut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(lblChocolateDonut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGlazedDonut2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtCdonut, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGdonut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(txtSdonut))
                                        .addGap(79, 79, 79)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblChocolateShake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblStrawberryShake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addComponent(lblHotChocolate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblType2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUN1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtStrawShake, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtChocShake, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHotChoco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(lblTax20, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGlazedDonut8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmountPaid))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTheSubTotal)
                                .addGap(0, 0, 0))
                            .addComponent(lblTaxation, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSub, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGlazedDonut7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChange, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTheTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddUp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlRedbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUN1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblDonuts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGlazedDonut2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHotChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGdonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHotChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChocolateDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChocolateShake, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCdonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChocShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStrawberryDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStrawberryShake, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSdonut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStrawShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTax20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGlazedDonut8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTaxation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTheTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTax)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTheSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGlazedDonut7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSub)
                    .addComponent(lblChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * void method to minimize UI
     * @param evt 
     */
    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked
    
    /**
     * void method to exit UI
     * @param evt 
     */
    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnConfirmationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmationMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnConfirmationMouseClicked
    
    /**
     * void method for confirm button
     * calculate change from amount paid
     * determine if payment is selected
     * @param evt 
     */
    private void btnConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmationActionPerformed
        // TODO add your handling code here:
        amountChange();
        
    }//GEN-LAST:event_btnConfirmationActionPerformed
    
    /**
     * void method to identify if payment is selected
     */
    public void paymentSelected(){
        
        if (cbbPaymentType.getSelectedItem().equals("Card") || cbbPaymentType.getSelectedItem().equals("Cash")){
            System.out.println("Payment Verified");
        }
        else if (cbbPaymentType.getSelectedItem().equals("Payment")){
            emptyPayment();
        }
        else{
            System.out.println("ERROR in payment!");
        }
    }
    
    /**
     * void method to get the change from amount paid
     */
    public void amountChange(){
        DecimalFormat df = new DecimalFormat("0.00");
        
        try{
        double finalTotal = getTotal();
        double amountPaid = getAmount();
        emptyFields();
        paymentSelected();
        
        if (amountPaid == finalTotal || amountPaid > finalTotal){
            double change = amountPaid - finalTotal;
            lblChange.setText("£" + df.format(change));
        }
        else{
            System.out.println("Not enough money");
            noMoney();
        }}
        catch(Exception errorMessage){
            System.out.println("Amount Paid is Empty or is Not a Number");
            //errorMessage.printStackTrace();
        }
    }
    
    /**
     * void method to return to previous page
     * @param evt 
     */
    private void btnGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBackMouseClicked
        // TODO add your handling code here:
        loginPage lp = new loginPage();
        lp.setVisible(true);
        lp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lp.setLocationRelativeTo(null);
        lp.pack();    
        this.dispose();
    }//GEN-LAST:event_btnGoBackMouseClicked

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetDetails();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUpMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnAddUpMouseClicked
    
    /**
     * void method to direct to not enough money screen
     */
    public void noMoney(){
        notEnoughCash nec = new notEnoughCash();
        nec.setVisible(true);
        nec.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        nec.setLocationRelativeTo(null);
        nec.pack();    
        this.dispose();
    }
    
    /**
     * void method to link to empty detail page
     */
    public void emptyDetails2(){
        EmptyDetails2 ed = new EmptyDetails2();
        ed.setVisible(true);
        ed.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ed.setLocationRelativeTo(null);
        ed.pack();    
        this.dispose();
    }
    
    /**
     * void method to link to empty payment page
     */
    public void emptyPayment(){
        EmptyPayment ep = new EmptyPayment();
        ep.setVisible(true);
        ep.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ep.setLocationRelativeTo(null);
        ep.pack();    
        this.dispose();
    }
    
    
    /**
     * void method to link to not numeric page
     */
    public void notNumbers(){
        notNumeric nn = new notNumeric();
        nn.setVisible(true);
        nn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        nn.setLocationRelativeTo(null);
        nn.pack();    
        this.dispose();
    }
    
    /**
     * void method to validate empty fields
     */
    private void emptyFields(){
        
        try{
        if (txtGdonut.getText().isEmpty()
            || txtCdonut.getText().isEmpty()
            || txtSdonut.getText().isEmpty() 
            || txtHotChoco.getText().isEmpty() 
            || txtChocShake.getText().isEmpty()
            || txtStrawShake.getText().isEmpty()
            || txtAmountPaid.getText().isEmpty())
        {
            emptyDetails2();
        }
        else
        {
            
        }
        }
        catch(Exception errorMessage){
            System.out.println("Some Fields are Empty");
            //errorMessage.printStackTrace();
        }
        
    }
    
    /**
     * void method to determine if input is not numeric
     */
    private void notNumeric(){
              
        String validInput = "^[0-9]*$";
        
        try{
        if (!txtGdonut.getText().matches(validInput) 
            || !txtSdonut.getText().matches(validInput)
            || !txtCdonut.getText().matches(validInput)
            || !txtHotChoco.getText().matches(validInput)
            || !txtChocShake.getText().matches(validInput)
            || !txtStrawShake.getText().matches(validInput)
            || !txtAmountPaid.getText().matches(validInput))
        {
            notNumbers();
        }
        else
        {
            
        }
        }
        catch(Exception errorMessage){
            System.out.println("Input is Not Valid");
        }
        
    }
    
    
    /**
     * method for add up button
     * @param evt 
     */
    private void btnAddUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUpActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("0.00");
        
        
        double amount = getSubTotal();
        double newTax = getTax(amount);
        double total = getAddedTax(amount);
        
        lblTax.setText("£" + df.format(newTax));
        lblSub.setText("£" + df.format(getSubTotal()));
        lblTotal.setText("£" + df.format(total));
        
        emptyFields();
        notNumeric();
        
    }//GEN-LAST:event_btnAddUpActionPerformed
    
    private void cbbPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbPaymentTypeActionPerformed
    
    /**
     * Getter for the amount paid
     * @return returns the amount of money paid
     */
    public double getAmount(){
         
        double amount = Double.parseDouble(txtAmountPaid.getText());  
        double newAmount = amount;
        
        return newAmount;
        
    }
    
    /**
     * Getter for total cost of order
     * @return returns the total
     */
    public double getTotal(){
        double subTotal = getSubTotal();
        double finalTotal = getAddedTax(subTotal);
        
        return finalTotal;
    }
    
    /**
     * Add calculated tax to order
     * @param subtotal parameter for subtotal
     * @return returns the added tax
     */
    public double getAddedTax(double subtotal){
        
        double tax = 0.20 * subtotal;
        double total = subtotal + tax;
        
        return total;
    }
    
    /**
     * Calculate tax of item
     * @param subtotal parameter for subtotal of order
     * @return returns the tax
     */
    public double getTax(double subtotal){
        double tax = 0.20 * subtotal;
        return tax;
    }
    
    /**
     * Getter for sub total
     * @return returns the sub total
     */
    public double getSubTotal(){
        
     try{
        double glazedD = Double.parseDouble(txtGdonut.getText());
        double chocalateD = Double.parseDouble(txtCdonut.getText());
        double strawberryD = Double.parseDouble(txtSdonut.getText());
        double hotChocolate = Double.parseDouble(txtHotChoco.getText());
        double chocolateShake = Double.parseDouble(txtChocShake.getText());
        double strawberryShake = Double.parseDouble(txtStrawShake.getText());
        
        double glazedDcost = glazedD * gDonut;
        double chocolateDcost = chocalateD * cDonut;
        double strawberryDcost = strawberryD * sDonut;
        double hotChocolateCost = hotChocolate * hChocolate;      
        double chocolateShakeCost = chocolateShake * cShake;
        double strawberryShakeCost = strawberryShake * sShake;
        
        donuts = glazedDcost + chocolateDcost + strawberryDcost;
        drinks = hotChocolateCost + chocolateShakeCost + strawberryShakeCost;
        
        totalOfDonutsDrinks = donuts + drinks;
        allTotal = totalOfDonutsDrinks;
       
        
    }
     catch(Exception errorMessage){
        System.out.println("Input is Invalid, Must be Number");
        //errorMessage.printStackTrace();
    }
        return allTotal;
    }
    
    /**
     * void method to reset details
     */
    public void resetDetails(){
        
        try{
        txtGdonut.setText("0");
        txtCdonut.setText("0");
        txtSdonut.setText("0");
        txtHotChoco.setText("0");
        txtStrawShake.setText("0");
        txtChocShake.setText("0");
        
        lblTotal.setText("");
        lblTax.setText("");
        lblSub.setText("");
        lblChange.setText("");
        txtAmountPaid.setText("0");
        cbbPaymentType.setSelectedItem("Payment");
    } catch(Exception errorMessage){
            System.out.println("Something Went Wrong When Resetting");
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itemsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUp;
    private javax.swing.JButton btnConfirmation;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbbPaymentType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JLabel lblAmountPaid;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblChocolateDonut;
    private javax.swing.JLabel lblChocolateShake;
    private javax.swing.JLabel lblDonuts;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGlazedDonut2;
    private javax.swing.JLabel lblGlazedDonut7;
    private javax.swing.JLabel lblGlazedDonut8;
    private javax.swing.JLabel lblHotChocolate;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblSignUpScreen;
    private javax.swing.JLabel lblStrawberryDonut;
    private javax.swing.JLabel lblStrawberryShake;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTax20;
    private javax.swing.JLabel lblTaxation;
    private javax.swing.JLabel lblTheSubTotal;
    private javax.swing.JLabel lblTheTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblType2;
    private javax.swing.JLabel lblUN1;
    private javax.swing.JPanel pnlRedbar1;
    private javax.swing.JTextField txtAmountPaid;
    private javax.swing.JTextField txtCdonut;
    private javax.swing.JTextField txtChocShake;
    private javax.swing.JTextField txtGdonut;
    private javax.swing.JTextField txtHotChoco;
    private javax.swing.JTextField txtSdonut;
    private javax.swing.JTextField txtStrawShake;
    // End of variables declaration//GEN-END:variables

}
