package OOP;


import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JFrame;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henry
 */
public class SignUpPage extends javax.swing.JFrame {
        
    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlRedbar1 = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblSignUpScreen = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        lblUN = new javax.swing.JLabel();
        lblUN1 = new javax.swing.JLabel();
        lblUN7 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        lblUN9 = new javax.swing.JLabel();
        lblUN10 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPhoneNO = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnCreateAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        pnlRedbar1.setBackground(new java.awt.Color(51, 255, 204));

        lblExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblExit.setForeground(java.awt.Color.white);
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(java.awt.Color.white);
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("-");
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        lblSignUpScreen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSignUpScreen.setForeground(java.awt.Color.white);
        lblSignUpScreen.setText("SIGN-UP");

        javax.swing.GroupLayout pnlRedbar1Layout = new javax.swing.GroupLayout(pnlRedbar1);
        pnlRedbar1.setLayout(pnlRedbar1Layout);
        pnlRedbar1Layout.setHorizontalGroup(
            pnlRedbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRedbar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSignUpScreen)
                .addGap(30, 30, 30))
        );
        pnlRedbar1Layout.setVerticalGroup(
            pnlRedbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRedbar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRedbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSignUpScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnGoBack.setBackground(new java.awt.Color(51, 255, 204));
        btnGoBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Go Back");
        btnGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoBackMouseClicked(evt);
            }
        });
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        lblUN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUN.setForeground(new java.awt.Color(255, 255, 255));
        lblUN.setText("Username:");

        lblUN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUN1.setForeground(new java.awt.Color(255, 255, 255));
        lblUN1.setText("Password:");

        lblUN7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUN7.setForeground(new java.awt.Color(255, 255, 255));
        lblUN7.setText("Re-enter:");

        txtPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword2ActionPerformed(evt);
            }
        });

        lblUN9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUN9.setForeground(new java.awt.Color(255, 255, 255));
        lblUN9.setText("Phone NO:");

        lblUN10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUN10.setForeground(new java.awt.Color(255, 255, 255));
        lblUN10.setText("E-mail:");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtPhoneNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNOActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnCreateAccount.setBackground(new java.awt.Color(51, 255, 204));
        btnCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRedbar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUN1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUN7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUN10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUN9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNO, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlRedbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUN1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUN7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUN9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUN10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAccount)
                    .addComponent(btnGoBack))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * void method to exit UI
     * @param evt 
     */
    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked
    
    /**
     * Set action for minimize button 
     * to minimize GUI
     * @param evt 
     */
    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPhoneNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNOActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGoBackActionPerformed
    
    /**
     * Set code for back button 
     * to return to previous screen
     * @param evt 
     */
    private void btnGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBackMouseClicked
        // TODO add your handling code here:
        loginPage lp = new loginPage();
        lp.setVisible(true);
        lp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnGoBackMouseClicked
    
    /**
     * Invalid phone number validation
     * and dialog message
     */
    public void invalidPhone(){
        InvalidPhone ip = new InvalidPhone();
        ip.setVisible(true);
        ip.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ip.setLocationRelativeTo(null);
        ip.pack();  
        this.dispose();
    }
    
    /**
     * Invalid email validation
     * and dialog message
     */
    public void invalidEmail(){
        InvalidEmail ie = new InvalidEmail();
        ie.setVisible(true);
        ie.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ie.setLocationRelativeTo(null);
        ie.pack();
        this.dispose();
    }
    
    /**
     * Empty details validation
     * and dialog message
     */
    public void emptyDetails(){
        EmptyDetails ed = new EmptyDetails();
        ed.setVisible(true);
        ed.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ed.setLocationRelativeTo(null);
        ed.pack();    
        this.dispose();
    }
    
    /**
     * Invalid password validation
     * and dialog message
     */
    public void invalidPassword(){
        InvalidPasswordMatch ip = new InvalidPasswordMatch();
        ip.setVisible(true);
        ip.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ip.setLocationRelativeTo(null);
        ip.pack();  
        this.dispose();
    }
    
    /**
     * Direct to items page
     */
    public void itemsPage(){
        itemsPage ip = new itemsPage();
        ip.setVisible(true);
        ip.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ip.setLocationRelativeTo(null);
        ip.pack();
        this.dispose();
    }
           
     /**
     * Code for create account button 
     * to accept new information
     * @param evt 
     */
    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        
        String userName = txtUsername.getText();
        String passWord = txtPassword.getText();
        String passWord2 = txtPassword2.getText();
        String phoneNO = txtPhoneNO.getText();
        String eMail = txtEmail.getText();
        
        String invalidCharacters = "[0-9*#+() -]*";
        String emailValidation =  "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        
        if (phoneNO.equals("") || eMail.equals("")){
           emptyDetails();       
        }
        else if (userName.equals("") || passWord.equals("") ){
           emptyDetails(); 
        }    
        else if(!eMail.matches(emailValidation)){
            invalidEmail();    
        }
        else if(phoneNO.matches(invalidCharacters) && phoneNO.length() != 11){
            invalidPhone();
        }
        else if (passWord.equals(passWord2)){
            itemsPage();
            addTXTfile(userName, passWord, "newCustomers.txt");
            addFullData(userName, passWord, phoneNO, eMail, "fullData.txt");        
        }                 
        else{
            invalidPassword();           
        }
      
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void txtPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword2ActionPerformed
    
    /**
     * Add user to system
     * @param username parameter for username
     * @param password parameter for password
     * @param fileName parameter for fileName
     */
     public void addTXTfile(String username, String password, String fileName){
        
         try{
         BufferedWriter writeFile = new BufferedWriter(new FileWriter(fileName, true)); 
            
         writeFile.write("\n" + username + ", " + password); 
         writeFile.close(); 
        
        }
         catch(Exception errorMessage){
             System.out.println("ERROR!, Something went wrong");
         }
                  
    }
   
    /**
     * Add staff details to file
     * @param username parameter for username
     * @param password parameter for password
     * @param email parameter for email
     * @param phone parameter for phone
     * @param fileName parameter for file name
     */
    public void addFullData(String username, String password, String email, 
                                String phone, String fileName){
        
        try{
         BufferedWriter writeFull = new BufferedWriter(new FileWriter(fileName, true)); 
            
         writeFull.write("\n" + username + ", " + password + ", " + email + ", "
                            + phone); 
         writeFull.close(); 
        
        }
         catch(Exception errorMessage){
             System.out.println("ERROR!, Something went wrong");
         } 
        
    } 
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSignUpScreen;
    private javax.swing.JLabel lblUN;
    private javax.swing.JLabel lblUN1;
    private javax.swing.JLabel lblUN10;
    private javax.swing.JLabel lblUN7;
    private javax.swing.JLabel lblUN9;
    private javax.swing.JPanel pnlRedbar1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtPhoneNO;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
